name: wellbeing
description: "A new Flutter project."
publish_to: 'none'
version: 1.4.3+10

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.1.1
  badges: ^3.1.1
  dio: ^5.3.3
  image_picker: ^1.0.7
  another_flushbar: ^1.12.29
  image_cropper: ^5.0.1
  maps_toolkit: ^2.0.1
  url_launcher: ^6.1.10
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  rxdart: ^0.27.7
  logger: ^1.3.01
  intl: ^0.19.0
  flutter_image_slideshow: ^0.1.6
  loading_animation_widget: ^1.2.1
  flutter_email_sender: ^6.0.2
  change_app_package_name: ^1.1.0
  http: ^1.2.1
  material_icons_named: ^3.16.0
  universal_io: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/HAPPPY-CLUB.png"
  min_sdk_android: 21 
  web:
    generate: true
    image_path: "assets/images/HAPPPY-CLUB.png"
  windows:
    generate: true
    image_path: "assets/images/HAPPPY-CLUB.png"
    icon_size: 48 
  macos:
    generate: true
    image_path: "assets/images/HAPPPY-CLUB.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Sukhumvit
      fonts:
        - asset: assets/fonts/SukhumvitSet-Light.ttf
        - asset: assets/fonts/SukhumvitSet-Bold.ttf
        - asset: assets/fonts/SukhumvitSet-Medium.ttf
        - asset: assets/fonts/SukhumvitSet-SemiBold.ttf
        - asset: assets/fonts/Sukhumvitset.ttf
